### ISSUE TITLE
`make install` results in `error: no such module 'SourceKittenFramework'`

### ISSUE THREAD

**Issue by ildarsharafutdinov** [ilyapuchka/dipgen#2]
hi,

I follow your installation instruction and get the error

```
The following build commands failed:
	CompileSwift normal x86_64
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)
make: *** [installables] Error 65
```

It looks like `SourceKittenFramework ` is missed:
```
/Users/ildar/Workspace/ildarshara/github/ilyapuchka/dipgen/DipGenFramework/Sources/CodeGenerator.swift:10:8: error: no such module 'SourceKittenFramework'
import SourceKittenFramework
       ^
```

I use carthage 0.18.1 and Xcode 8.

Any ideas what goes wrong?

**Comment by ildarsharafutdinov** [comment]
```
git show
commit 0e9277fe51a9fe2f53ec3453ec224dfa6f111bae
Merge: 7eac9f6 79d5223
Author: Ilya Puchka <ilyapuchka@gmail.com>
Date:   Tue Nov 29 22:29:46 2016 +0100

    Merge pull request #1 from ilyapuchka/release/1.0.2
    
    Release 1.0.2
```

**Comment by ilyapuchka** [comment]
Probably you don't have SourceKitten installed on your machine

**Comment by ildarsharafutdinov** [comment]
```
sourcekitten version
0.16.0
```

SourceKitten is available on my machine.

Is 0.16.0 a compatible version?
Are there any other dependencies?

**Comment by ilyapuchka** [comment]
No, since 0.15.0 SourceKitten is Swift 3, but dipgen is built with Swift 2.3 and uses SourceKitten 0.14.1

**Comment by ildarsharafutdinov** [comment]
```
sourcekitten version
0.14.1

ls /usr/local/Frameworks/
CarthageKit.framework		SourceKittenFramework.framework
```

SourceKitten 0.14.1 and SourceKittenFramework.framework is in place, however the error remains...

Any ideas what went wrong are welcome.

**Comment by ilyapuchka** [comment]
Have you tried installing from the package attached to release?

**Comment by ilyapuchka** [comment]
The framework dependencies are simply not built if you just clone the project. You can do `carthage build --platform macOS && make install` or to install from the package attached to the release. I updated instructions in readme. Thanks for spotting the problem.
