### ISSUE TITLE
Ошибка запуска фазы сборки

### ISSUE THREAD

**Issue by dehrom** [ilyapuchka/dipgen#3]
Здравствуйте.
При запуске dipgen сталкиваюсь с ошибкой:
![2017-01-26 15 00 49](https://cloud.githubusercontent.com/assets/5616690/22330648/5aa2ee42-e3d8-11e6-805c-5a2723769c29.png)
Теряюсь в догадках что же пошло не так.

**Comment by ilyapuchka** [comment]
Боюсь без самого скрипта буду сам теряться в догадках...
